/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  admin_dashboard: () => import("@/views/admin/dashboard/index.vue"),
  "admin_library_book-category": () => import("@/views/admin/library/book-category/index.vue"),
  "admin_library_book-chapter-rule": () => import("@/views/admin/library/book-chapter-rule/index.vue"),
  "admin_library_book-filter-rule": () => import("@/views/admin/library/book-filter-rule/index.vue"),
  "admin_library_book-tag": () => import("@/views/admin/library/book-tag/index.vue"),
  admin_library_book: () => import("@/views/admin/library/book/index.vue"),
  admin_system_dept: () => import("@/views/admin/system/dept/index.vue"),
  admin_system_dict: () => import("@/views/admin/system/dict/index.vue"),
  admin_system_log: () => import("@/views/admin/system/log/index.vue"),
  admin_system_menu: () => import("@/views/admin/system/menu/index.vue"),
  admin_system_role: () => import("@/views/admin/system/role/index.vue"),
  "admin_system_user-detail": () => import("@/views/admin/system/user-detail/[id].vue"),
  admin_system_user: () => import("@/views/admin/system/user/index.vue"),
  home: () => import("@/views/home/index.vue"),
};
