/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'admin',
    path: '/admin',
    component: 'layout.base',
    meta: {
      title: 'admin',
      i18nKey: 'route.admin'
    },
    children: [
      {
        name: 'admin_dashboard',
        path: '/admin/dashboard',
        component: 'view.admin_dashboard',
        meta: {
          title: 'admin_dashboard',
          i18nKey: 'route.admin_dashboard'
        }
      },
      {
        name: 'admin_library',
        path: '/admin/library',
        meta: {
          title: 'admin_library',
          i18nKey: 'route.admin_library'
        },
        children: [
          {
            name: 'admin_library_book',
            path: '/admin/library/book',
            component: 'view.admin_library_book',
            meta: {
              title: 'admin_library_book',
              i18nKey: 'route.admin_library_book'
            }
          },
          {
            name: 'admin_library_book-category',
            path: '/admin/library/book-category',
            component: 'view.admin_library_book-category',
            meta: {
              title: 'admin_library_book-category',
              i18nKey: 'route.admin_library_book-category'
            }
          },
          {
            name: 'admin_library_book-chapter-rule',
            path: '/admin/library/book-chapter-rule',
            component: 'view.admin_library_book-chapter-rule',
            meta: {
              title: 'admin_library_book-chapter-rule',
              i18nKey: 'route.admin_library_book-chapter-rule'
            }
          },
          {
            name: 'admin_library_book-filter-rule',
            path: '/admin/library/book-filter-rule',
            component: 'view.admin_library_book-filter-rule',
            meta: {
              title: 'admin_library_book-filter-rule',
              i18nKey: 'route.admin_library_book-filter-rule'
            }
          },
          {
            name: 'admin_library_book-tag',
            path: '/admin/library/book-tag',
            component: 'view.admin_library_book-tag',
            meta: {
              title: 'admin_library_book-tag',
              i18nKey: 'route.admin_library_book-tag'
            }
          }
        ]
      },
      {
        name: 'admin_system',
        path: '/admin/system',
        meta: {
          title: 'admin_system',
          i18nKey: 'route.admin_system'
        },
        children: [
          {
            name: 'admin_system_dept',
            path: '/admin/system/dept',
            component: 'view.admin_system_dept',
            meta: {
              title: 'admin_system_dept',
              i18nKey: 'route.admin_system_dept'
            }
          },
          {
            name: 'admin_system_dict',
            path: '/admin/system/dict',
            component: 'view.admin_system_dict',
            meta: {
              title: 'admin_system_dict',
              i18nKey: 'route.admin_system_dict'
            }
          },
          {
            name: 'admin_system_log',
            path: '/admin/system/log',
            component: 'view.admin_system_log',
            meta: {
              title: 'admin_system_log',
              i18nKey: 'route.admin_system_log'
            }
          },
          {
            name: 'admin_system_menu',
            path: '/admin/system/menu',
            component: 'view.admin_system_menu',
            meta: {
              title: 'admin_system_menu',
              i18nKey: 'route.admin_system_menu'
            }
          },
          {
            name: 'admin_system_role',
            path: '/admin/system/role',
            component: 'view.admin_system_role',
            meta: {
              title: 'admin_system_role',
              i18nKey: 'route.admin_system_role'
            }
          },
          {
            name: 'admin_system_user',
            path: '/admin/system/user',
            component: 'view.admin_system_user',
            meta: {
              title: 'admin_system_user',
              i18nKey: 'route.admin_system_user'
            }
          },
          {
            name: 'admin_system_user-detail',
            path: '/admin/system/user-detail/:id',
            component: 'view.admin_system_user-detail',
            meta: {
              title: 'admin_system_user-detail',
              i18nKey: 'route.admin_system_user-detail',
              hideInMenu: true
            }
          }
        ]
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      hideInMenu: true
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  }
];
